---
s:: true
---
---
s:: true
---
---
s:: true
---

This worked until I tried to install Conda through Linux with the following:
(Conda install in order to create a Conda environment from an `environment.yml` file)


`borge@Borge$ wget https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh`

returning this:

![Pasted image 20230216125914.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230216125914.png)

After this I changed the permissions of the downloaded file so that it can execute.

`borge@Borge:~$ chmod +x Anaconda3-2019.10-Linux-x86_64.sh`

after this I then executed the file with

`borge@Borge:~$ sh ./Anaconda3-2019.10-Linux-x86_64.sh`

returning

![Pasted image 20230216130327.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230216130327.png)
I then confirmed the location; which returned:

![Pasted image 20230216130504.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230216130504.png)

and now VS-code returns the error:
![Pasted image 20230216130533.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230216130533.png)

`df` returns:

![Pasted image 20230216130943.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230216130943.png)

`ls -l` in destination folder returns:
![Pasted image 20230216131100.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230216131100.png)

and `ls -l` in Conda folder returns:

![Pasted image 20230216131158.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230216131158.png)

## Thoughts from Borge:

```
Could not remove or rename /home/borge/conda/pkgs/pango-1.42.4-h049681c_0tvjgx1st/pkg-pango-1.42.4-h049681c_0.tar.zst.  Please remove this file manually (you may need to reboot to free file handles)

Could not remove or rename /home/borge/conda/pkgs/python-3.7.4-h265db76_1gbpm3rry/pkg-python-3.7.4-h265db76_1.tar.zst.  Please remove this file manually (you may need to reboot to free file handles)

Could not remove or rename /home/borge/conda/pkgs/gevent-1.4.0-py37h7b6447c_0iaofrsfx/pkg-gevent-1.4.0-py37h7b6447c_0.tar.zst.  Please remove this file manually (you may need to reboot to free file handles)

``` 

This seems to be the main problem - will go into files and remove manually


## Thoughts from AI:

given error message AI returns:
![Pasted image 20230216132822.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230216132822.png)
then asking what may have halted the install returns:

![Pasted image 20230216132903.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230216132903.png)

on next attempt will bare the advice in mind


===============================================================

tried unregistering WSL and starting again this time with installing Conda right away following:

- http://mmb.irbbarcelona.org/molywood/tutorials/windows_sub
one thing to note for this method when going through it with dad is to ignore the sh and just run: `./Anaconda3-2019.10-Linux-x86_64.sh` instead of `sh ./Anaconda3-2019.10-Linux-x86_64.sh`

but this meant that Conda was used as the main python path and as a result Jax would not work.

had to do the same thing again:

# when the Jupyter doesn't like pip use : 
# `sudo apt-get update` 
# this will update the source and stop the issue



# 2023-02-16 18:50 

- have got WSL working again without putting in any of my own personal notebook or `.py` files 
- will now try installing Conda
- have now installed Conda and nothing has broken WOOOOOOOOO
- now need to create a Conda environment form the `environment.yml` file - how exactly not sure
- says Conda is not found?
- running creating Conda environment directly in ubuntu
- ![Pasted image 20230216191338.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230216191338.png)
- has been swirling for ages - not sure how to end the process either - feel like this should be quicker

# 20:00

- came back after dinner to massive failure and now VS-code is unable to start with error: [WSL was interrupted unexpectedly] - was with friends so didn't have time to screenshot


# 2023-02-17 10:00

- turned computer on and ubuntu opened saying:
- ![Pasted image 20230217101515.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230217101515.png)
- Wait cancel that that is the wrong ubuntu

# WE ARE USING UBUNTU 20.04

- VScode opens the directories but says:
- ![Pasted image 20230217101101.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230217101101.png)
- going to select interpreter: [CONDA]
- it works...?
- ran test notebook successfully using the Conda interpreter


## 2023-02-17 16:19

- trying to create the conda environment in the terminal with:
- ![Pasted image 20230217162005.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230217162005.png)
- ![Pasted image 20230217162026.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230217162026.png)
- taking ages on this step
- ![Pasted image 20230217162357.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230217162357.png)
- seems like it just takes a while
- ![Pasted image 20230217163140.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230217163140.png)
- its doing something
- errored again:
```

    Traceback (most recent call last):
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1074, in __call__
        return func(*args, **kwargs)
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 78, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 102, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda_env/installers/conda.py", line 32, in install
        unlink_link_transaction.execute()
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 244, in execute
        self.verify()
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 221, in verify
        self.prepare()
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 213, in prepare
        stp.neutered_specs)
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 288, in _prepare
        for prec, pcrec in zip(link_precs, pkg_cache_recs_to_link))
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 288, in <genexpr>
        for prec, pcrec in zip(link_precs, pkg_cache_recs_to_link))
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 100, in read_package_info
        paths_data = read_paths_json(epd)
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 170, in read_paths_json
        data = json.load(paths_json)
      File "/home/borge/anaconda3/lib/python3.7/json/__init__.py", line 296, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "/home/borge/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
        return _default_decoder.decode(s)
      File "/home/borge/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/borge/anaconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ /home/borge/anaconda3/bin/conda-env create -f /home/borge/ficl/environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/borge/anaconda3/bin/conda
             CONDA_PREFIX=/home/borge/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/borge/anaconda3/bin/python
               CONDA_ROOT=/home/borge/anaconda3
              CONDA_SHLVL=1
                     PATH=/home/borge/anaconda3/bin:/home/borge/.vscode-
                          server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/bin/remote-cli:/ho
                          me/borge/.local/bin:/home/borge/anaconda3/bin:/home/borge/anaconda3/co
                          ndabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/u
                          sr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/System32/HWA
                          udioDriverLibs:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/S
                          ystem32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Win
                          dows/System32/OpenSSH:/mnt/c/Users/Administrator/AppData/Local/Microso
                          ft/WindowsApps:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/S
                          ystem32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WIN
                          DOWS/System32/OpenSSH:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/georg/
                          AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/georg/AppData/Local/G
                          itHubDesktop/bin:/mnt/c/Users/georg/AppData/Local/Programs/Microsoft
                          VS Code/bin:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/borge/anaconda3
            shell level : 1
       user config file : /home/borge/.condarc
 populated config files : 
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : 
       base environment : /home/borge/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/borge/anaconda3/pkgs
                          /home/borge/.conda/pkgs
       envs directories : /home/borge/anaconda3/envs
                          /home/borge/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/5.15.79.1-microsoft-standard-WSL2 ubuntu/20.04.3 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

says that it failed on the transaction

### thoughts from AI

The error message `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` indicates that there was an issue with trying to read a JSON file or string. Specifically, the error message suggests that the JSON parser expected to find a value (e.g. a string, number, boolean, null, or an object/array made up of these types) at the beginning of the file, but instead found no content at all (hence `column 1 (char 0)`).

In this case, the error occurred when running the `conda-env` command with the argument `create -f /home/borge/ficl/environment.yml`. This suggests that the `environment.yml` file is either empty or not a properly formatted YAML file. To resolve the issue, you should check the contents of `environment.yml` to ensure that it is a valid YAML file with the necessary information to create the environment.

- everything still runs though

- ![Pasted image 20230217171829.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230217171829.png)
- Noticed that we are on a very old conda here so have updated conda
- returning:
- ![Pasted image 20230217171942.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230217171942.png)
- going to try again and see what happens with new conda
- collecting packages again - done
- solving environment - taking ages - still taking ages - failed:
```

    Traceback (most recent call last):
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1074, in __call__
        return func(*args, **kwargs)
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 78, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 102, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda_env/installers/conda.py", line 32, in install
        unlink_link_transaction.execute()
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 244, in execute
        self.verify()
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 221, in verify
        self.prepare()
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 213, in prepare
        stp.neutered_specs)
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 288, in _prepare
        for prec, pcrec in zip(link_precs, pkg_cache_recs_to_link))
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 288, in <genexpr>
        for prec, pcrec in zip(link_precs, pkg_cache_recs_to_link))
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 100, in read_package_info
        paths_data = read_paths_json(epd)
      File "/home/borge/anaconda3/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 170, in read_paths_json
        data = json.load(paths_json)
      File "/home/borge/anaconda3/lib/python3.7/json/__init__.py", line 296, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "/home/borge/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
        return _default_decoder.decode(s)
      File "/home/borge/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/borge/anaconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ /home/borge/anaconda3/bin/conda-env create -f /home/borge/ficl/environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/borge/anaconda3/bin/conda
             CONDA_PREFIX=/home/borge/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/borge/anaconda3/bin/python
               CONDA_ROOT=/home/borge/anaconda3
              CONDA_SHLVL=1
                     PATH=/home/borge/anaconda3/bin:/home/borge/.vscode-
                          server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/bin/remote-cli:/ho
                          me/borge/.local/bin:/home/borge/anaconda3/bin:/home/borge/anaconda3/co
                          ndabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/u
                          sr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/System32/HWA
                          udioDriverLibs:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/S
                          ystem32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Win
                          dows/System32/OpenSSH:/mnt/c/Users/Administrator/AppData/Local/Microso
                          ft/WindowsApps:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/S
                          ystem32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WIN
                          DOWS/System32/OpenSSH:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/georg/
                          AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/georg/AppData/Local/G
                          itHubDesktop/bin:/mnt/c/Users/georg/AppData/Local/Programs/Microsoft
                          VS Code/bin:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/borge/anaconda3
            shell level : 1
       user config file : /home/borge/.condarc
 populated config files : 
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : 
       base environment : /home/borge/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/borge/anaconda3/pkgs
                          /home/borge/.conda/pkgs
       envs directories : /home/borge/anaconda3/envs
                          /home/borge/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/5.15.79.1-microsoft-standard-WSL2 ubuntu/20.04.3 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```
 
- failing on the same bit:

 ```linux
 raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
``` 
can't work out

- conda still seems to be on an old version running:
`conda update --all` ![Pasted image 20230217174712.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230217174712.png)
![Pasted image 20230217174712.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230217174712.png)
- ![Pasted image 20230217174639.png](../../../AA%20%20-%20%20Assets/Pasted%20image%2020230217174639.png)
- 
- 